# Generated by Django 2.1.3 on 2018-11-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_auto_20181113_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='processor_id',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requester_id',
            new_name='requester',
        ),
    ]
