# Generated by Django 2.1.3 on 2018-11-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_auto_20181113_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_looged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'NORMAL'), ('2', 'HR'), ('3', 'MANAGER')], default='1', max_length=100),
        ),
    ]
