# Generated by Django 2.1.3 on 2018-11-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('HR Reviewed', 'HR Reviewed'), ('Processed', 'Processed')], default='Open', max_length=20),
        ),
    ]
