# Generated by Django 2.1.3 on 2018-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0008_auto_20181114_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'EMPLOYEE'), ('2', 'HR'), ('3', 'MANAGER')], default='1', max_length=100),
        ),
    ]
